config/routes.rb
Crudify::Engine.routes.draw do
  
  resources :cruds
  get 'crudify/export_delta_json' =>'cruds#export_delta_json'
  root "cruds#index"
  get 'delete_content', to: 'cruds#delete_content'
end

app/controllers/crudify/cruds_controller.rb
module Crudify
  class CrudsController < ApplicationController
    layout 'crudify_base'

    before_action :init

    def index
      if current_user.present? && Rails.application.config.content_engine[:is_auth_enabled]
          authorize current_user, :create_provider_and_location?
      end

      @contents = @model_class.all rescue ::Department.all
    end

    def new
      if current_user.present? && Rails.application.config.content_engine[:is_auth_enabled]
          authorize current_user, :create_provider_and_location?
      end

      @content = @model_class.new
    end

    def create
      if current_user.present? && Rails.application.config.content_engine[:is_auth_enabled]
          authorize current_user, :create_provider_and_location?
      end

      model = params[:model]
      form_attr = params[model.underscore]
      form_obj  = model.constantize.new()
      form_attr.each do |k|
        if form_obj.send(k[0]).class.eql?(Array)
          form_obj[k[0]] = [JSON.parse(form_attr[k[0]].gsub('[','').gsub(']', '').gsub('=>', ':'))]
        else
          form_obj[k[0]] =  k[1]
        end
      end
      form_obj.save
      redirect_to cruds_path({model: @model})
    end

    def edit
      if current_user.present? && Rails.application.config.content_engine[:is_auth_enabled]
          authorize current_user, :create_provider_and_location?
      end

      @content =  @model_class.find_by_id(params[:id])
    end

    def update
      if current_user.present? && Rails.application.config.content_engine[:is_auth_enabled]
          authorize current_user, :create_provider_and_location?
      end

      form_attr = params[@model.underscore.to_sym]
      content_obj =  @model_class.find_by_id(params[:id])
      form_attr.each do |k|
        if content_obj.send(k[0]).class.eql?(Array)
          content_obj[k[0]] = [JSON.parse(form_attr[k[0]].gsub('[','').gsub(']', '').gsub('=>', ':'))]
        else
          content_obj[k[0]] =  k[1]
        end
      end
      content_obj.save
      redirect_to cruds_path({model: @model})
    end

    private

    def init
      @model = params[:model]
      parent_class = self.class.superclass
      @model_class = parent_class.const_get(@model) rescue Department
    end
  end
end

app/helpers/crudify/cruds_helper.rb
module Crudify 
  module CrudsHelper

    def content_tag_helper(col_name, obj, options = {}, disabled=false)
      form_obj = obj.class.to_s.underscore
      value =  obj.send(col_name)
      
      if options[:attr].present?  
        opt = options[:attr].split(',') 
        field_type = opt[0] rescue 'txt'
        disabled = (opt[1].eql?("1") ? false : true) rescue false
      else
        field_type = 'txt'
        disabled = false
      end 
      data_type = options[:datatype]
      skip_relation = obj.class&.skip_relation&.respond_to?(:include?) && obj.class&.skip_relation.include?(col_name)
      tag = if col_name.match(/_id$/) && !skip_relation
             # is_polymorphic = obj.class.polymorphic_content&.delete_if{|n| n.eql?(:polymorphic_content) }
              content = obj.class.respond_to?(:polymorphic_content) ? obj.class.polymorphic_content : nil
              is_polymorphic = content.is_a?(Array) ? content.delete_if { |n| n.eql?(:polymorphic_content) } : nil
              if is_polymorphic.blank?
                poly_model =  obj.class.reflections.select { |name, reflection| reflection.options[:polymorphic] == true }
                model = poly_model.keys.first
              else
                model = ""
              end
              
              if !is_polymorphic.blank? && col_name.match(model)
                collection1 = nil
                is_polymorphic.each do |poly_model|
                  col_arr = poly_model.to_s.camelize.constantize.all.collect{|s| [ "#{s.class.name} - #{s.send(s.class.relational_display_col)}", s.id ] } rescue []
                  collection1.nil? ? collection1 = col_arr : collection1.concat(col_arr)
                end         
              else
                relational_model = col_name.to_s.split(/_id$/)[0].capitalize
                collection1 = relational_model.camelize.constantize.all.collect{|s| [s.send(s.class.relational_display_col), s.id ] } rescue []
              end
              collection1.unshift(["--- Select Empty ---", ""])
              select_tg(col_name, form_obj, value, collection1, disabled=false)
            elsif field_type.eql?('enum')
              collection =  obj.class.send("#{col_name}s").keys
              collection.unshift(["--- Select Empty ---", ""])
              select_tg(col_name, form_obj, value, collection, disabled=false)
            elsif data_type.eql?(:boolean) 
              select_tg(col_name, form_obj, value, [true, false], disabled=false)
            elsif data_type.eql?(:text) 
              txt_box_area(col_name, form_obj, value, disabled=false)  
            else
              txt_box(col_name, form_obj, value, disabled)
            end
      tag
    end

    def polymorphic_select(obj, col_name)    
      models = obj.class.polymorphic_content.delete_if{|n| n.eql?(:polymorphic_content) }
      collection =  models.map { |s| s.to_s.classify }
    end

    def txt_box(col_name, form_obj, value, disabled=false)
      text_field_tag("#{form_obj}[#{col_name}]", value, disabled: disabled, class: "input-field" )
    end
    
    def txt_box_area(col_name, form_obj, value, disabled=false)
      text_area_tag("#{form_obj}[#{col_name}]", value, disabled: disabled, class: "input-field", size: "30x15"  )
    end

    def select_tg(col_name, form_obj, value, collection, disabled=false) 
      select_tag("#{form_obj}[#{col_name}]", options_for_select(collection, value), class: "select-field")
    end

    def get_action_tag(obj)
      non_archived = ArchiveLog.where(class_id: obj.id, class_type: obj.class.name, action: 'delete', is_exported: false )
      if non_archived.present?
        return  "<span style='color:red;font-weight:bold;'> DELETED </span>"
      else 
        return nil
      end
    end

    def get_child_action_tag(obj, child_obj_class)
      non_archived = ArchiveLog.where(class_id: obj.id, class_type: obj.class.name, action: 'delete', is_exported: false )
      if non_archived.present?
        return  "<span style='color:red;font-weight:bold;'> DELETED #{child_obj_class} </span></br></br>"
      else 
        return nil
      end
    end

    def delete_count(obj)
      ArchiveLog.unarchived_deleted(obj.name).count
    end

  end
end

app/views/crudify/cruds/partials/_edit.html.erb
<div class="form-style-2-heading">Update <%= @content.class %>  </div>
<%= link_to 'Go Back to Content List', cruds_path(model: @content.class) %>

<div class="form-style-2">
  <%= form_with model: @content, url: "/crudify/cruds/#{@content.id}",  method: :put do |f| %>
    <%= render "crudify/cruds/shared/form", content: @content, f: f %>
  <% end %>
</div>

app/views/crudify/cruds/partials/_index.html.erb
<style>
    table, th, td {
        border: 2px solid #F5F0F5;
        margin: 10px 10px 10px 10px;
        padding: 10px 10px 10px 10px;
    }
</style>
<br/>
<%= link_to "Add new #{@contents.first.class}", new_crud_path(model: @contents.first.class) %>
<br/>
<% if @contents.present? %>
  <div class="form-style-2-heading"><%= @contents.first.class.to_s.titleize %> Listing </div>


  <br/><br/>

  <div style="overflow: hidden;width: 100%;">
    <table class="table table-bordered" style="overflow-x: auto;width: 100%;margin: 0;">
      <tbody>
      <tr>
        <% @contents.first.class.crud_col_hash.keys.each do |ct|  %>
          <th style="background-color:#F5F0F5;"><%= ct.to_s.humanize.capitalize %></th>
        <%end%>
        <th style="background-color:#F5F0F5;"> Action  </th>
      </tr>
      <% @contents.each do |cont| %>
        <tr>
          <% @contents.first.class.crud_col_hash.keys.each do |ct|  %>
            <td style="max-width: 200px;overflow: hidden; white-space: normal;text-overflow: ellipsis;">
              <% if ct.match(/_id$/) %>
                <% relational_model = ct.to_s.split(/_id$/)[0] %>
                <% relational_obj = cont.send(relational_model) %>
                <%= relational_obj.send(relational_obj.class.relational_display_col) %>
              <%else%>
                <%= cont.send(ct) %>
              <%end%>
            </td>
          <%end%>
          <td><%= link_to "Edit",  edit_crud_path(cont, model: cont.class), query: {model: cont.class} %> </td>
        </tr>
      <% end %>
      <tbody>
      </table>
  </div>
<% else %>

<% end %>

app/views/crudify/cruds/partials/_new.html.erb
<div class="form-style-2-heading">Update <%= @content.class %>  </div>
<%= link_to 'Go Back to Content List', cruds_path(model: @content.class) %>


<div class="form-style-2">
  <%= form_with model: @content, url: "/crudify/cruds",  method: :post do |f| %>
    <%= render "crudify/cruds/shared/form", content: @content, f: f %>
  <% end %>
</div>