config/routes.rb
Crudify::Engine.routes.draw do
  
  resources :cruds
  get 'crudify/export_delta_json' =>'cruds#export_delta_json'
  root "cruds#index"
  get 'delete_content', to: 'cruds#delete_content'
end

app/views/layouts/crudify_base.html.erb
<!DOCTYPE html>
<html style="height:100%;">
<head>
  <title><%#= Settings.application_name %></title>
  <meta property="og:title" content="<%#= Settings.application_name %>" />
  <link href="/favicon.ico" rel="icon" type="image/x-icon" />
  <link href="/favicons/apple-touch-icon.png" rel="apple-touch-icon" type="image/png" sizes="180x180" />
  <link href="/favicons/favicon-32x32.png" rel="icon" type="image/png" sizes="32x32" />
  <link href="/favicons/favicon-16x16.png" rel="icon" type="image/png" sizes="16x16" />
  <link rel="manifest" href="/favicons/manifest.json">

  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#ffffff">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
 
  <style>
  * {
    box-sizing: border-box;
  }

  body {
    font-family: Arial, Helvetica, sans-serif;
  }

  /* Style the header */
  header {
    background-color: <%= Rails.application.config.content_engine[:main_theme_color] %>;
    padding: 10px;
    text-align: center;
    font-size: 25px;
    color: white;
  }

  /* Container for flexboxes */
  section {
    display: -webkit-flex;
    display: flex;
  }

  /* Style the navigation menu */
  nav {
    background: #F5F0F5;
    min-width: 200px;
    padding: 40px 10px 10px 10px;
  }

  .left-panel {
    float: left;
    width: 200px;
    padding: 20px;
  }


  /* Style the list inside the menu */
  nav ul {
    list-style-type: none;
    padding: 0;
  }

  /* Style the content */
  article {
    -webkit-flex: 3;
    -ms-flex: 3;
    flex: 3;
    width: calc(100% - 200px);
    background-color: <%= Rails.application.config.content_engine[:secondary_theme_color] %>;
    padding: 10px;
  }

  /* Style the footer */
  footer {
    background-color: #8A6E93;
    border-bottom: 1px solid #ddd;
    font-size: 20px;
    text-align: center;
    color: white;

  }

  .form-style-2{
    max-width: 500px;
    padding: 20px 12px 10px 20px;
    font: 13px Arial, Helvetica, sans-serif;
  }
  .form-style-2-heading{
    font-weight: bold;
    font-style: italic;
    border-bottom: 2px solid #ddd;
    margin-bottom: 20px;
    font-size: 15px;
    padding-bottom: 3px;
  }
  .form-style-2 label{
    display: block;
    margin: 0px 0px 15px 0px;
  }
  .form-style-2 label > span{
    width: 170px;
    font-weight: bold;
    float: left;
    padding-top: 8px;
    padding-right: 5px;
  }
  .form-style-2 span.required{
    color:red;
  }
  .form-style-2 .tel-number-field{
    width: 40px;
    text-align: center;
  }
  .form-style-2 input.input-field, .form-style-2 .select-field{
    width: 48%;	
  }
  .form-style-2 input.input-field, 
  .form-style-2 .tel-number-field, 
  .form-style-2 .textarea-field, 
  .form-style-2 .select-field{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    border: 1px solid #C2C2C2;
    box-shadow: 1px 1px 4px #EBEBEB;
    -moz-box-shadow: 1px 1px 4px #EBEBEB;
    -webkit-box-shadow: 1px 1px 4px #EBEBEB;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    padding: 7px;
    outline: none;
  }
  .form-style-2 .input-field:focus, 
  .form-style-2 .tel-number-field:focus, 
  .form-style-2 .textarea-field:focus,  
  .form-style-2 .select-field:focus{
    border: 1px solid #0C0;
  }
  .form-style-2 .textarea-field{
    height:100px;
    width: 55%;
  }
  .form-style-2 input[type=submit],
  .form-style-2 input[type=button]{
    border: none;
    padding: 8px 15px 8px 15px;
    background: #FF8500;
    color: #fff;
    box-shadow: 1px 1px 4px #DADADA;
    -moz-box-shadow: 1px 1px 4px #DADADA;
    -webkit-box-shadow: 1px 1px 4px #DADADA;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
  }
  .form-style-2 input[type=submit]:hover,
  .form-style-2 input[type=button]:hover{
    background: #EA7B00;
    color: #fff;
  }

  /* Responsive layout - makes the menu and the content (inside the section) sit on top of each other instead of next to each other */
  @media (max-width: 600px) {
    section {
      -webkit-flex-direction: column;
      flex-direction: column;
    }
  }
</style>  
</head>
<body style="height:100%; display:flex; flex-direction:column;" >
<% if(Rails.application.config.content_engine[:is_auth_enabled] ? user_signed_in? : true) %>
<header>
  Content Management
</header>

<section style="flex: 1;">
  <nav>
    <% Rails.application.config.content_engine[:content_models].each do |content| %>
    <ul>
      <li><%= link_to content.titleize, cruds_path(model: content) %></li>
    </ul>
    <%end%>
  </nav>
  
  <article>
    <%= yield %>
  </article>
</section>

<footer>
  <p><%= Rails.application.config.content_engine[:application_name]%> </p>
</footer>
  <% else %>
  <meta http-equiv="refresh" content="0; url=/users/sign_in">
  <% end %>
</body>
</html>